# Generated by Django 2.2.24 on 2021-07-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='assets/newsletters')),
                ('meta', models.CharField(max_length=30)),
                ('frequency', models.IntegerField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(related_name='tags', to='tags.Tag')),
                ('users', models.ManyToManyField(related_name='users', to='users.User')),
            ],
        ),
    ]
